In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

In [31]:
sequence = np.array([0,1,1,2,3,5,8,13,21,34])

In [32]:
def create_dataset(sequence, n_steps):
  X, y = [], []
  for i in range (len(sequence)):
    end_ix = i + n_steps
    if end_ix > len(sequence)-1:
      break
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return np.array(X), np.array(y)

In [41]:
n_steps = 2
X, y = create_dataset(sequence, n_steps)
#print(X)
#print(y)
X = X.reshape(X.shape[0], X.shape[1],1)
print(X)

[[[ 0]
  [ 1]]

 [[ 1]
  [ 1]]

 [[ 1]
  [ 2]]

 [[ 2]
  [ 3]]

 [[ 3]
  [ 5]]

 [[ 5]
  [ 8]]

 [[ 8]
  [13]]

 [[13]
  [21]]]


In [42]:
model = Sequential()
model.add(SimpleRNN(50, activation='relu', input_shape=(n_steps,1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [43]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (None, 50)                2600      
                                                                 
 dense_3 (Dense)             (None, 1)                 51        
                                                                 
Total params: 2651 (10.36 KB)
Trainable params: 2651 (10.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [44]:
model.fit(X, y, epochs=2000, verbose=0)
#verbose=0 does not show the process
#verbose=1 shows the process [=========]

In [45]:
x_input = np.array([21,34])
x_input = x_input.reshape((1, n_steps, 1))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[54.42288]]
