In [9]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

In [10]:
sequence = np.array([0,1,4,9,16,25,36,49,64,81,100,121])

In [11]:
def create_dataset(sequence, n_steps):
  X, y = [], []
  for i in range (len(sequence)):
    end_ix = i + n_steps
    if end_ix > len(sequence)-1:
      break
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return np.array(X), np.array(y)

In [12]:
n_steps = 5
X, y = create_dataset(sequence, n_steps)
#print(X)
#print(y)
X = X.reshape(X.shape[0], X.shape[1],1)
print(X)

[[[  0]
  [  1]
  [  4]
  [  9]
  [ 16]]

 [[  1]
  [  4]
  [  9]
  [ 16]
  [ 25]]

 [[  4]
  [  9]
  [ 16]
  [ 25]
  [ 36]]

 [[  9]
  [ 16]
  [ 25]
  [ 36]
  [ 49]]

 [[ 16]
  [ 25]
  [ 36]
  [ 49]
  [ 64]]

 [[ 25]
  [ 36]
  [ 49]
  [ 64]
  [ 81]]

 [[ 36]
  [ 49]
  [ 64]
  [ 81]
  [100]]]


In [13]:
model = Sequential()
model.add(SimpleRNN(50, activation='relu', input_shape=(n_steps,1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [14]:
model.fit(X, y, epochs=2000, verbose=0)
#verbose=0 does not show the process
#verbose=1 shows the process [=========]

In [15]:
x_input = np.array([49,64,81,100,121])
x_input = x_input.reshape((1, n_steps, 1))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[146.54341]]
